Full Name: Mohammadmahdi Bababeyk

Student ID:4041419005

# Introduction to PyTorch

**Goal:**  
Understand what PyTorch is, how to create and manipulate **tensors**, and perform simple mathematical operations.  

## What is PyTorch?

[PyTorch](https://pytorch.org/) is a powerful open-source **deep learning framework** developed by Facebook (Meta).  
It is popular because it’s:
- **Pythonic** — works naturally with Python syntax  
- **Dynamic** — computations run immediately (no static graphs)  
- **Flexible** — allows tensor operations, GPU acceleration, and building complex neural networks easily  

In PyTorch, the **core data structure** is the **Tensor**, which is very similar to a NumPy array but optimized for deep learning.


## Importing PyTorch and checking the version

In [10]:
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.9.0+cu126


## What is a Tensor?

A **Tensor** is a multi-dimensional array — similar to a NumPy array — that can:
- Store numbers of different types (`float`, `int`, `bool`, etc.)
- Move between CPU and GPU easily
- Support fast mathematical operations

Tensors are the foundation of PyTorch computations.

## Creating Tensors

There are several common ways to create tensors:

In [11]:
# From a Python list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print("Tensor from list:\n", x_data)

# From a NumPy array
import numpy as np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print("\nTensor from NumPy array:\n", x_np)

# Using built-in functions
x_ones = torch.ones((2, 3))    # All ones
x_zeros = torch.zeros((2, 3))  # All zeros
x_rand = torch.rand((2, 3))    # Random values between 0 and 1
x_full = torch.full((2, 3), 5) # All filled with 5
print("\nOnes:\n", x_ones)
print("\nZeros:\n", x_zeros)
print("\nRandom:\n", x_rand)
print("\nFull of 5s:\n", x_full)

Tensor from list:
 tensor([[1, 2],
        [3, 4]])

Tensor from NumPy array:
 tensor([[1, 2],
        [3, 4]])

Ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

Random:
 tensor([[0.8071, 0.6786, 0.5220],
        [0.6042, 0.5266, 0.6134]])

Full of 5s:
 tensor([[5, 5, 5],
        [5, 5, 5]])


### Explanation:
- `torch.tensor(data)` → creates a tensor directly from Python data.  
- `torch.from_numpy()` → shares memory with the NumPy array (changes in one reflect in the other).  
- `torch.ones`, `torch.zeros`, `torch.rand`, and `torch.full` are convenient initialization functions.


## Tensor Shapes and Dtypes

In [12]:
# Example tensor
x = torch.rand((3, 4))

print("Tensor:\n", x)
print("\nShape:", x.shape)
print("Number of elements:", x.numel())
print("Data type:", x.dtype)
print("Device:", x.device)

Tensor:
 tensor([[0.6889, 0.5274, 0.9158, 0.0619],
        [0.4628, 0.6131, 0.2121, 0.1157],
        [0.1346, 0.9963, 0.2949, 0.1088]])

Shape: torch.Size([3, 4])
Number of elements: 12
Data type: torch.float32
Device: cpu


### Explanation:
- `.shape` → the dimensions of the tensor  
- `.numel()` → total number of elements  
- `.dtype` → data type (e.g., float32, int64)  
- `.device` → tells whether the tensor is stored on **CPU** or **GPU**

## Moving Tensors to GPU (if available)

PyTorch allows you to use GPUs seamlessly.  
Let’s check if CUDA (GPU support) is available.

In [13]:
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

x_cpu = torch.ones((2, 2))
x_gpu = x_cpu.to(device)

print("Device used:", device)
print("Tensor on CPU:", x_cpu)
print("Tensor moved to:", x_gpu.device)

Device used: cuda
Tensor on CPU: tensor([[1., 1.],
        [1., 1.]])
Tensor moved to: cuda:0


### Explanation:
- `torch.cuda.is_available()` checks if a GPU is accessible.  
- `.to(device)` moves a tensor between CPU and GPU.  
- Tensor operations automatically run on the device where the tensor lives.

## Basic Tensor Operations

In [14]:
# Create two tensors
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# Element-wise operations
print("Addition:\n", a + b)
print("\nSubtraction:\n", a - b)
print("\nMultiplication (element-wise):\n", a * b)
print("\nDivision:\n", a / b)

# Matrix multiplication
print("\nMatrix multiplication (dot product):\n", torch.matmul(a, b))
# or equivalently
print("\nUsing @ operator:\n", a @ b)

Addition:
 tensor([[ 6.,  8.],
        [10., 12.]])

Subtraction:
 tensor([[-4., -4.],
        [-4., -4.]])

Multiplication (element-wise):
 tensor([[ 5., 12.],
        [21., 32.]])

Division:
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

Matrix multiplication (dot product):
 tensor([[19., 22.],
        [43., 50.]])

Using @ operator:
 tensor([[19., 22.],
        [43., 50.]])


### Explanation:
- Arithmetic operators (`+`, `-`, `*`, `/`) are element-wise.  
- `torch.matmul()` or `@` performs **matrix multiplication** (dot product).  
- These operations return *new tensors* — the originals stay unchanged.

## Tensor Indexing & Slicing

In [15]:
# Create sample tensor
tensor = torch.arange(16).reshape(4, 4)
print("Tensor:\n", tensor)

# Indexing
print("\nFirst row:", tensor[0])
print("Last column:", tensor[:, -1])
print("Middle 2x2 block:\n", tensor[1:3, 1:3])

# Changing elements
tensor[0, 0] = 999
print("\nAfter modifying first element:\n", tensor)

Tensor:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

First row: tensor([0, 1, 2, 3])
Last column: tensor([ 3,  7, 11, 15])
Middle 2x2 block:
 tensor([[ 5,  6],
        [ 9, 10]])

After modifying first element:
 tensor([[999,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15]])


### Explanation:
- `tensor[row, column]` accesses elements  
- `:` means “all elements” along that dimension  
- Tensors are mutable — you can assign values directly to parts of them


## Reshaping Tensors

In [16]:
x = torch.arange(12)
print("Original:\n", x)

x_reshaped = x.reshape(3, 4)
print("\nReshaped to 3x4:\n", x_reshaped)

x_view = x.view(2, 6)
print("\nViewed as 2x6:\n", x_view)

x_transposed = x_reshaped.T
print("\nTransposed (swapped dimensions):\n", x_transposed)

Original:
 tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped to 3x4:
 tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Viewed as 2x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

Transposed (swapped dimensions):
 tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


### Explanation:
- `.reshape()` creates a new tensor with a different shape (copy or view depending on memory layout).  
- `.view()` is similar but requires the data to be contiguous in memory.  
- `.T` or `.transpose()` swaps dimensions.

## Practice 1

**Task:**  
1. Create a 3×3 tensor filled with random integers between 10 and 50  
2. Convert it to a float tensor  
3. Compute its mean and standard deviation  
4. Reshape it into a 1D tensor of 9 elements

*(Hint: use `torch.randint`, `.float()`, `.mean()`, `.std()`, `.reshape()`)*

In [17]:
# 1. Create a 3×3 tensor with random integers between 10 and 50 (inclusive)
tensor_int = torch.randint(10, 51, (3, 3))
print("Original Integer Tensor:\n", tensor_int)

# 2. Convert to float tensor
tensor_float = tensor_int.float()

# 3. Compute mean and standard deviation
mean_value = tensor_float.mean()
std_value = tensor_float.std()

print(f"\nMean: {mean_value}")
print(f"Standard Deviation: {std_value}")

# 4. Reshape into a 1D tensor of 9 elements
tensor_flat = tensor_float.reshape(-1)
print("\nReshaped 1D Tensor:\n", tensor_flat)

Original Integer Tensor:
 tensor([[22, 20, 29],
        [13, 16, 42],
        [16, 24, 27]])

Mean: 23.22222137451172
Standard Deviation: 8.814445495605469

Reshaped 1D Tensor:
 tensor([22., 20., 29., 13., 16., 42., 16., 24., 27.])


## Practice 2

**Task:**  
Create two tensors of shape (2, 3) and:
- Add and multiply them element-wise  
- Perform matrix multiplication between one and the transpose of the other  
- Move one tensor to GPU (if available) and check its device

In [18]:
# 1. Create two tensors of shape (2, 3) ---
data1 = [[1, 2, 3], [4, 5, 6]]
data2 = [[7, 8, 9], [10, 11, 12]]

tensor_a = torch.tensor(data1)
tensor_b = torch.tensor(data2)

print("Tensor A:\n", tensor_a)
print("Tensor B:\n", tensor_b)

# 2. Element-wise addition and multiplication ---
elementwise_sum = tensor_a + tensor_b
elementwise_mul = tensor_a * tensor_b

print("\nElement-wise Sum:\n", elementwise_sum)
print("\nElement-wise Multiplication:\n", elementwise_mul)

# 3. Matrix multiplication (A @ B^T) ---
matrix_product = tensor_a @ tensor_b.T
print("\nMatrix Multiplication (A @ B^T):\n", matrix_product)

# 4. Move tensor to GPU (if available) ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tensor_a_gpu = tensor_a.to(device)
print(f"\nTensor A on device: {tensor_a_gpu.device}")

Tensor A:
 tensor([[1, 2, 3],
        [4, 5, 6]])
Tensor B:
 tensor([[ 7,  8,  9],
        [10, 11, 12]])

Element-wise Sum:
 tensor([[ 8, 10, 12],
        [14, 16, 18]])

Element-wise Multiplication:
 tensor([[ 7, 16, 27],
        [40, 55, 72]])

Matrix Multiplication (A @ B^T):
 tensor([[ 50,  68],
        [122, 167]])

Tensor A on device: cuda:0
